adminUser: admin
adminPassword: admin

persistence:
  type: pvc
  enabled: true

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    # Allow discovery in all namespaces for dashboards
    searchNamespace: ALL

  # datasources:
  #   enabled: true
  #   # label that the configmaps with datasources are marked with
  #   label: grafana_datasource
  #   # value of label that the configmaps with datasources are set to
  #   labelValue: "1"
  #   # If specified, the sidecar will search for datasource config-maps inside this namespace.
  #   # Otherwise the namespace in which the sidecar is running will be used.
  #   # It's also possible to specify ALL to search in all namespaces
  #   searchNamespace: ALL

## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:

    # For prometheus helm
    # - name: Prometheus
    #   uid: prometheus    
    #   type: prometheus
    #   access: proxy
    #   orgId: 1
    #   url: http://prometheus-server.prometheus.svc
    #   basicAuth: false
    #   isDefault: true
    #   jsonData:
    #     httpMethod: POST
    #     timeInterval: 30s

    # For kube-prometheus-stack helm
    - name: Prometheus
      uid: prometheus    
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
      basicAuth: false
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s

    # For prometheus helm
    # - name: Alertmanager
    #   uid: alertmanager    
    #   type: alertmanager
    #   access: proxy
    #   orgId: 1
    #   url: http://prometheus-alertmanager.prometheus.svc:9093
    #   basicAuth: false
    #   isDefault: false
    #   jsonData:
    #     handleGrafanaManagedAlerts: false
    #     implementation: prometheus

    # For kube-prometheus-stack helm
    - name: Alertmanager
      uid: alertmanager    
      type: alertmanager
      access: proxy
      orgId: 1
      url: http://prometheus-kube-prometheus-alertmanager.monitoring:9093/
      basicAuth: false
      isDefault: false
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus

    - name: influxdb
      uid: influxdb    
      type: influxdb
      access: proxy
      orgId: 1
      url: http://influxdb.influxdb.svc:8086
      basicAuth: false
      isDefault: false
      jsonData:
        dbName: k6_go_app
        httpMode: POST
        oauthPassThru: false
        timeInterval: 15s
        timeout: 300
        tlsAuth: false
        tlsAuthWithCACert: false
        tlsSkipVerify: false
    - name: loki
      uid: loki    
      type: loki
      access: proxy
      orgId: 1
      url: http://loki.loki.svc:3100
      basicAuth: false
      isDefault: false
      jsonData:
        timeout: 300
    - name: tempo
      uid: tempo    
      type: tempo
      access: proxy
      orgId: 1
      url: http://tempo.tempo.svc:3100
      basicAuth: false
      isDefault: false
      jsonData: {}
