apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
spec:
  replicas: 1 #number of replicas generated  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # The maxSurge property controls the maximum number of additional pods that can be created during a rolling update
      maxUnavailable: 1 # The maxUnavailable property determines the maximum number or percentage of pods that can be unavailable during a rolling update
      # maxSurge: 25%
      # maxUnavailable: 25%
  selector:
    # Assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/app: zookeeper
  template:
    metadata:      
      labels:
        app.kubernetes.io/app: zookeeper
        istio: monitor
    spec:
      # serviceAccountName: zookeeper-sa
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.8
        imagePullPolicy: IfNotPresent
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
          seccompProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 2181
          name: http
        resources:          
          requests:
            cpu: "1"
            memory: 4Gi
          limits:
            cpu: "1"
            memory: 4Gi
        volumeMounts:
        - mountPath: /bitnami
          name: zookeeper-data
          readOnly: true
      volumes:
      - name: zookeeper-data
        hostPath:
          path: /bitnami
          # type: DirectoryOrCreate