apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: zookeeper-http
      port: 2181
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/app: zookeeper