apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9092
      protocol: TCP
      targetPort: http
    - name: external
      port: 9094
      protocol: TCP
      targetPort: external
  selector:
    app.kubernetes.io/app: kafka