# -- Section for crafting Promtails config file. The only directly relevant value is `config.file`
# which is a templated string that references the other values and snippets below this key.
# @default -- See `values.yaml`
config:
  clients:
    - url: http://loki.loki.svc:3100/loki/api/v1/push