apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kube-state-metrics-podmonitor
  namespace: proxy-monitoring
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  podMetricsEndpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 15s