services:

  jenkins:
    build: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro            
    depends_on:
      - docker-dind
    networks:
      - jenkins

  docker-dind:
    # image: docker:dind
    build: ./docker/dind
    container_name: docker-in-docker
    privileged: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    networks:
      jenkins:
        aliases:
          - docker
      
  docker-registry:
    image: registry:2.8.3
    container_name: docker-registry
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: "/tls/server.crt"
      REGISTRY_HTTP_TLS_KEY: "/tls/server.pem"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./docker/dind/tls:/tls
    networks:
      jenkins:
        aliases:
          - registry

  # app:
  #   image: node:16-alpine
  #   container_name: app
  #   command: tail -F /dev/null
    
networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
    external: false
  jenkins-docker-certs:
    external: false