apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
  namespace: debian
  labels:
    app.kubernetes.io/name: debian
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/name: debian
  template:
    metadata:
      labels:
        app.kubernetes.io/name: debian
    spec:
      containers:
      - name: debian-bookworm
        image: debian:12.11
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi