# apiVersion: v1
# kind: Service
# metadata:
#   name: valkey-service
#   namespace: valkey
# spec:
#   type: ClusterIP
#   ports:
#     - port: 6379
#       targetPort: valkey-port
#       name: valkey-http
#   selector:
#     app.kubernetes.io/name: valkey