apiVersion: v1
kind: Service
metadata:
  name: valkey-headless-svc-stateful
  namespace: valkey
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: valkey-port
      name: valkey-http
      protocol: TCP
  selector:
    app.kubernetes.io/name: valkey