{
 "title": "Istio dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(istio_requests_total,namespace)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(istio_requests_total{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "response_code",
    "query": {
     "query": "label_values(istio_requests_total,response_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(istio_requests_total{pod=~\"$pod_name\", namespace=~\"$namespace\", response_code=~\"$response_code\"}[30s])",
     "legendFormat": "{{pod}} | {{response_code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{pod=~\"$pod_name\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{pod=~\"$pod_name\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{pod=~\"$pod_name\", namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Availability (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        istio_requests_total\n        {\n            pod=~\"$pod_name\",\n            namespace=~\"$namespace\",\n            response_code!~\"[4-5].*\"\n        }[1m])) by (destination_app) /\nsum(\n    rate(\n        istio_requests_total\n        {\n            pod=~\"$pod_name\",\n            namespace=~\"$namespace\"\n        }[1m])) by (destination_app)",
     "legendFormat": "Availability"
    }
   ]
  }
 ]
}