deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem # we're storing on filesystem so there's no real persistence here.
      schema: v13
singleBinary:
  replicas: 1
  persistence:
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: true
    # -- Enable persistent disk
    enabled: true
    # -- Size of persistent disk
    size: 10Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: standard
    # # -- Selector for persistent disk
    # selector: null
    # # -- Annotations for volume claim
    # annotations: {}
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0

gateway:
  enabled: false

memcached:
  chunk_cache:
    enabled: false
  results_cache:
      enabled: false

# memcached:
#   resources:
#     requests:
#       cpu: 1000m
#       memory: 4Gi
#     limits:
#       cpu: 2000m
#       memory: 6Gi

memcachedExporter:
  enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

chunksCache:
  allocatedMemory: 512

resultsCache:
  allocatedMemory: 256