services:
  k6:
    image: grafana/k6
    container_name: k6
    environment:
      - K6_OUT=influxdb=http://host.docker.internal:8086/k6_go_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./scripts:/scripts