{
 "title": "Envoy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "http_status",
    "query": {
     "query": "label_values(envoy_cluster_external_upstream_rq,envoy_response_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "envoy_cluster_external_upstream_rq_time_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(envoy_cluster_external_upstream_rq_time_bucket{envoy_cluster_name=\"mainapp_service\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(envoy_cluster_external_upstream_rq_time_bucket{envoy_cluster_name=\"mainapp_service\"}[1m])))",
     "legendFormat": "0.90"
    }
   ]
  },
  {
   "title": "envoy_cluster_upstream_rq_time_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"mainapp_service\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"mainapp_service\"}[1m])))",
     "legendFormat": "0.9"
    }
   ]
  },
  {
   "title": "Total request by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_external_upstream_rq) by (envoy_response_code)",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_cluster_external_upstream_rq",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}