apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
    - host: app.service.api
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: proxy-server
                port:
                  number: 80
