apiVersion: v1
kind: Namespace
metadata:
  name: authentication-service
  labels: 
    istio-injection: enabled # Set istio-injection for injection proxy sidecar and apply to pod that match with this namespace