apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
  labels:
    name: influxdb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8086
    targetPort: http
  selector:
    app: influxdb