{
 "title": "cAdvisor Monitoring & k6 Load Testing Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod_namespace",
    "query": {
     "query": "label_values(container_label_io_kubernetes_pod_namespace)"
    }
   },
   { "name": "node", "query": { "query": "label_values(node)" } },
   {
    "name": "Measurement",
    "query": "http_req_duration,http_req_blocked,http_req_connecting,http_req_looking_up,http_req_receiving,http_req_sending,http_req_waiting"
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values({container_label_io_kubernetes_pod_namespace=\"$pod_namespace\"},container_label_io_kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU usage % (1m avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum(machine_cpu_cores{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster memory usage % ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(machine_memory_bytes{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU usage % of the limit (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum(machine_cpu_cores{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Cluster memory usage % of the limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"}) / sum(machine_memory_bytes{namespace=\"cadvisor\", namespace=\"cadvisor\"}) * 100",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "CPU used (Cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{id=\"/\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU total (Cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{namespace=\"cadvisor\", namespace=\"cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{namespace=\"cadvisor\", namespace=\"cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Requests per Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT sum(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP req failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "http req failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP req duration (over time)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM http_req_duration WHERE $timeFilter and value > 0"
    }
   ]
  },
  {
   "title": "Virtual users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "query": "SELECT sum(\"value\") FROM \"vus\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "VUs Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus_max",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Pod resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Pods CPU throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(\n    container_cpu_cfs_throttled_seconds_total{\nimage!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n    }[1m]\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg) with requests and limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n}[1m])) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"cpu\",\n        unit=\"core\"\n    }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"cpu\",\n        unit=\"core\"\n    }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Pods memory usage with requests and limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n}) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"memory\",\n        unit=\"byte\"\n    }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests{\n        namespace=~\"$pod_namespace$\",\n        pod=~\"$pod_name$\",\n        resource=\"memory\",\n        unit=\"byte\"\n    }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\"\n}[1m])) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "{{container_label_io_kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(\n  container_network_receive_bytes_total{\n    image!=\"\",\n    name=~\"^k8s_.*\",\n    kubernetes_io_hostname=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\"\n  }[1m]\n) * 8",
     "legendFormat": "Receive - {{container_label_io_kubernetes_pod_name}}"
    },
    {
     "expr": "irate(\n  container_network_transmit_bytes_total{\n    image!=\"\",\n    name=~\"^k8s_.*\",\n    kubernetes_io_hostname=~\"^$Node$\",container_label_io_kubernetes_pod_namespace=~\"$pod_namespace$\",container_label_io_kubernetes_pod_name=~\"$pod_name$\"\n  }[1m]\n) * 8",
     "legendFormat": "Transmit - {{container_label_io_kubernetes_pod_name}}"
    }
   ]
  }
 ]
}