apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: go-app
  labels:
    app.kubernetes.io/name: go-app
spec:
  replicas: 2
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/name: go-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-app    
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: go-app
        image: host.minikube.internal:5000/go-app:1.0.0
        imagePullPolicy: Always      
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi