# kubectl create secret docker-registry regcred --docker-server=host.minikube.internal:5000 --docker-username=docker --docker-password=1234 -n go-app
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: go-app
data:
 .dockerconfigjson: eyJhdXRocyI6eyJob3N0Lm1pbmlrdWJlLmludGVybmFsOjUwMDAiOnsidXNlcm5hbWUiOiJkb2NrZXIiLCJwYXNzd29yZCI6IjEyMzQiLCJhdXRoIjoiWkc5amEyVnlPakV5TXpRPSJ9fX0=
type: kubernetes.io/dockerconfigjson