apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: go-app-server
  name: go-app-server
  namespace: go-app
spec:
  type: ClusterIP
  # type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: go-app