apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: curl
  labels:
    app.kubernetes.io/name: curl
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/name: curl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        imagePullPolicy: Always      
        ports:
        - containerPort: 3000
          name: http
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi