apiVersion: v1
kind: Service
metadata:
  name: redis-headless-svc-stateful
  namespace: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis-port
      name: redis-http
      protocol: TCP
    # - port: 9121
    #   targetPort: exporter-port
    #   name: redis-metrics
  selector:
    app.kubernetes.io/name: redis