apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-proxy
  namespace: go-app-proxy
  labels:
    app.kubernetes.io/name: go-app-proxy
spec:
  replicas: 1 #number of replicas generated  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # The maxSurge property controls the maximum number of additional pods that can be created during a rolling update
      maxUnavailable: 1 # The maxUnavailable property determines the maximum number or percentage of pods that can be unavailable during a rolling update
  selector:
    # Assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/name: go-app-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-app-proxy    
    spec:
      containers:
      # - name: envoy-sidecar
      #   image: envoyproxy/envoy:v1.33.0
      #   ports:
      #   - containerPort: 5055
      #     name: proxy
      #   - containerPort: 9901
      #     name: proxy-metric
      #   args:
      #   - "--config-path"
      #   - "/etc/envoy/envoy.yaml"
      #   volumeMounts:
      #   - name: envoy-config-volume
      #     mountPath: /etc/envoy
      - name: go-app
        image: go-app:2.0
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          runAsUser: 10001
          runAsGroup: 10001
          seccompProfile:
            type: RuntimeDefault         
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9000
          name: metrics
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 500m
            memory: 128Mi
      volumes:
      - name: envoy-config-volume
        configMap:
          name: envoy-config