apiVersion: v1
kind: Service
metadata:
  name: go-app-server
  namespace: go-app-proxy
  labels:
    app.kubernetes.io/name: go-app-server  
  # annotations:
  #   prometheus.io/port: "metrics"
  #   prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: proxy
    port: 5055
    protocol: TCP
    targetPort: proxy
  - name: proxy-metric
    port: 9901
    protocol: TCP
    targetPort: proxy-metric
  # - name: http
  #   port: 80
  #   protocol: TCP
  #   targetPort: http
  - name: metrics
    port: 9000
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: go-app-proxy