# kubectl create secret generic postgresql-secret --from-literal=user=admin --from-literal=password=password1234
kind: Secret
apiVersion: v1
metadata:
  name: postgresql-secret
  namespace: postgresql
type: Opaque
data:
  password: cGFzc3dvcmQxMjM0
  user: YWRtaW4=