# kubectl get storageclass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" # Set a default StorageClass
provisioner: k8s.io/minikube-hostpath