apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: postgresql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15.2-alpine3.17
          imagePullPolicy: "IfNotPresent"
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - ALL
          #   runAsNonRoot: true
          #   readOnlyRootFilesystem: true
          #   runAsUser: 10001
          #   runAsGroup: 10001
          #   seccompProfile:
          #     type: RuntimeDefault
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: 100m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 512Mi
          env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgresql-configmap
                key: database
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: password
          volumeMounts:
          - name: postgresql-persistent-storage
            mountPath: /var/lib/postgresql
          - name: postgresql-persistent-data-storage
            mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: postgresql-persistent-data-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi