apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-3
  namespace: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: redis-port
      name: redis-http
      nodePort: 30003
  selector:
    statefulset.kubernetes.io/pod-name: redis-3