server:
  affinity: ""
  # dev:
  #   enabled: true
  
  ha:
    enabled: true

    # raft: 
    #   enabled: true
    #   setNodeId: true
    #   config: |
    #     cluster_name = "vault-integrated-storage"
    #     storage "raft" {
    #         path    = "/vault/data/"
    #     }

    #     listener "tcp" {
    #         address = "[::]:8200"
    #         cluster_address = "[::]:8201"
    #         tls_disable = "true"
    #     }
    #     service_registration "kubernetes" {}
        
    replicas: 1

    # config is a raw string of default configuration when using a Stateful
    # deployment. Default is to use a Consul for its HA storage backend.
    # This should be HCL.
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "consul-consul-server:8500"
      }

ui:
  enabled: true
  externalPort: 8200