{
 "title": "Go app dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod_name",
    "query": {
     "query": "label_values({container_label_io_kubernetes_pod_namespace=\"go-app\"},container_label_io_kubernetes_pod_name)"
    }
   },
   {
    "name": "http_status",
    "query": {
     "query": "label_values(go_app_http_server_request_duration_seconds_count,status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_app_http_server_request_duration_seconds_count{status_code=~\"$http_status$\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total request by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_app_http_server_request_duration_seconds_count{status_code=~\"$http_status$\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg) with requests and limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{\n    image!=\"\",\n    name=~\"^k8s_.*\",\n    container_label_io_kubernetes_pod_namespace=\"go-app\",\n    container_label_io_kubernetes_pod_name=~\"$pod_name$\",container_label_io_kubernetes_docker_type=\"container\"\n}[1m])) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits{\n        namespace=\"go-app\",\n        pod=~\"$pod_name$\",\n        resource=\"cpu\",\n        unit=\"core\"\n    }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests{\n        namespace=\"go-app\",\n        pod=~\"$pod_name$\",\n        resource=\"cpu\",\n        unit=\"core\"\n    }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Pods memory usage with requests and limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_label_io_kubernetes_pod_namespace=\"go-app\",\ncontainer_label_io_kubernetes_pod_name=~\"$pod_name$\",\ncontainer_label_io_kubernetes_docker_type=\"container\"\n}) by (\n    container_label_io_kubernetes_pod_name\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_limits{\n        namespace=\"go-app\",\n        pod=~\"$pod_name$\",\n        resource=\"memory\",\n        unit=\"byte\"\n    }\n)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(\n    kube_pod_container_resource_requests{\n        namespace=\"go-app\",\n        pod=~\"$pod_name$\",\n        resource=\"memory\",\n        unit=\"byte\"\n    }\n)",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Request per second [rate 1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(go_app_http_server_request_duration_seconds_count{status_code=~\"$http_status$\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Request per second by path [rate 1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(go_app_http_server_request_duration_seconds_count{status_code=~\"$http_status$\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(go_app_http_server_request_duration_seconds_bucket{status_code=~\"$http_status$\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(go_app_http_server_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(go_app_http_server_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.90"
    }
   ]
  }
 ]
}