apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cadvisor-pod-monitor
  namespace: monitoring
  labels:
    # release: prometheus # release: prometheus is default value for matching a pod to scrap a metrics, Matches kube-prometheus-stack release label (if do not set specific value)
    prometheus: main
    app: prometheus    
spec:
  namespaceSelector:
    matchNames:
      - cadvisor
  selector:
    matchLabels:
      app: cadvisor
  podMetricsEndpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 15s