apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cadvisor-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus # Matches kube-prometheus-stack release label
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - cadvisor
  selector:
    matchLabels:
      app: cadvisor
  podMetricsEndpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 15s