---
# storage:
#   trace:
#     backend: s3
#     s3:
#       access_key: 'grafana-tempo'
#       secret_key: 'supersecret'
#       bucket: 'tempo-traces'
#       endpoint: 'tempo-minio:9000'
#       insecure: true
# MinIO storage configuration
# Note: MinIO should not be used for production environments. This is for demonstration purposes only.
# minio:
#   enabled: true
#   mode: standalone
#   rootUser: grafana-tempo
#   rootPassword: supersecret
#   buckets:
#     # Default Tempo storage bucket
#     - name: tempo-traces
#       policy: none
#       purge: false

# Specifies which trace protocols to accept by the gateway.
traces:
  # OpenTelemetry protocol
  otlp:
    grpc:
      enabled: true
    http:
      # -- Enable Tempo to ingest Open Telemetry HTTP traces
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false