# apiVersion: v1
# kind: Service
# metadata:
#   name: redis-service
#   namespace: redis
# spec:
#   type: ClusterIP
#   ports:
#     - port: 6379
#       targetPort: redis-port
#       name: redis-http
#     # - port: 9121
#     #   targetPort: exporter-port
#     #   name: redis-metrics
#   selector:
#     app.kubernetes.io/name: redis