apiVersion: v1
kind: Pod
metadata:
  name: k6
  namespace: k6
  labels:
    app: k6
spec:
  containers:
  - name: k6
    image: grafana/k6
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 200Mi