apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: adminer
  labels:
    app.kubernetes.io/name: adminer
spec:
  replicas: 1
  #number of replicas generated
  selector:
    #assigns labels to the pods for future selection
    matchLabels:
      app.kubernetes.io/name: adminer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi