apiVersion: v1
kind: Service
metadata:
  name: adminer-service
  namespace: adminer
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: adminer