---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    app.kubernetes.io/name: cadvisor-service
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    # targetPort: http
    targetPort: 8080
  selector:
    name: cadvisor