---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    release: prometheus # Matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
  - port: http