---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-app
  namespace: go-app
  labels:
    release: prometheus # Matches kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-app-server
  endpoints:
  - port: metrics
    interval: 15s
    scrapeTimeout: 15s