# kubectl apply -n argocd -f application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ittipol/Gitops.git
    targetRevision: HEAD
    path: mysql
    # directory:
    #   recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: mysql

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
